language: crystal

before_install: []

before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y libsfml-dev

script:
  - crystal tool format ./src --check
  - crystal tool format ./spec --check
  - crystal spec

  - crystal docs

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local-dir: "docs"
    on:
        branch: master
