language: crystal

before_install: []

before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxrandr-dev libudev-dev libopenal-dev libglew-dev libjpeg-dev libfreetype6-dev libsndfile-dev
  - wget -O sfml.zip https://www.sfml-dev.org/files/SFML-2.4.2-sources.zip
  - unzip sfml.zip
  - cd SFML-2.4.2/
  - cmake . && make && sudo make install
  - export PATH=$PATH:/usr/local/lib
  - export {LD_,}LIBRARY_PATH=$LIBRARY_PATH:/usr/local/lib
  - cd ..
  - curl -L -k "https://chipmunk-physics.net/release/ChipmunkLatest.tgz" | tar -xz
  - pushd Chipmunk*
  - sed -i '/CMP0042/d' CMakeLists.txt # https://github.com/slembcke/Chipmunk2D/issues/112
  - cmake -DBUILD_DEMOS=off . && make && sudo make install
  - export {LD_,}LIBRARY_PATH=$LIBRARY_PATH:$PWD/src
  - popd
  - git clone https://github.com/oprypin/crsfml crsfml
  - cd crsfml
  - crystal run generate.cr -- /usr/local/include
  - cmake . && make && sudo make install
  - export {LD_,}LIBRARY_PATH=$LIBRARY_PATH:$PWD/voidcsfml
  - export CRSFML=$PWD
  - cd ..
  - rm -rf lib/crsfml
  - ln -s $CRSFML lib/crsfml
  - ls -alR $CRSFML
  - echo $LIBRARY_PATH

script:
  - crystal tool format ./src --check
  - crystal spec
