#! /bin/bash

# execute in application root
cd "$(git rev-parse --show-toplevel)"

rm .git/hooks/pre-commit
rm .git/hooks/pre-push

ln -s ../../scripts/pre-commit .git/hooks/pre-commit
ln -s ../../scripts/pre-push .git/hooks/pre-push
