#! /bin/bash

# execute in application root
cd "$(git rev-parse --show-toplevel)"

mkdir -p lib
cd lib
rm -rf crsfml/
mkdir crsfml
cd crsfml
git clone https://github.com/oprypin/crsfml .
cmake . && make
