#! /bin/bash

# exit on error
set -e

# execute in application root
cd "$(git rev-parse --show-toplevel)"

# run tests
export LIBRARY_PATH="$PWD/lib/crsfml/voidcsfml"    # Used during linking
export LD_LIBRARY_PATH="$LIBRARY_PATH"             # Used when running a binary

crystal spec
